streamingvideos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('video.urls', namespace='video')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video/urls.py
# url - view - template

from django.urls import path, reverse_lazy
from .views import HomeVideos, HomePage, DetalhesVideos, PesquisaVideo, EditarPerfil, CriarConta
from django.contrib.auth import views as auth_view

app_name = 'video'

urlpatterns = [
    path('', HomePage.as_view(), name='homepage'),
    path('videos/', HomeVideos.as_view(), name='homevideos'),
    path('videos/<int:pk>', DetalhesVideos.as_view(), name='detalhesvideos'),
    path('pesquisa/', PesquisaVideo.as_view(), name='pesquisavideo'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('editarperfil/<int:pk>', EditarPerfil.as_view(), name='editarperfil'),
    path('criarconta/', CriarConta.as_view(), name='criarconta'),
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name='editarperfil.html',
                                                             success_url=reverse_lazy('video:homevideos')), name='mudarsenha'),
]

video/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

LISTA_CATEGORIAS = (
    ("HUMOR", "Humor"),
    ("ACAO", "Ação"),
    ("CIENCIA", "Ciência"),
    ("HORROR", "Horror"),
    ("FANTASIA", "Fantasia"),
    ("OUTROS", "Outros"),
)
class Filme(models.Model):
    titulo = models.CharField(max_length=100)
    thumb = models.ImageField(upload_to='thumb_filmes')
    descricao = models.TextField(max_length=1000)
    categoria = models.CharField(max_length=20, choices=LISTA_CATEGORIAS)
    visualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)
    objects = models.Manager()

    def __str__(self):
        return self.titulo


# Episódios
class Episodio(models.Model):
    filme = models.ForeignKey("Filme", related_name="episodios", on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    video = models.URLField()

    def __str__(self):
        return self.filme.titulo + ' - ' + self.titulo

class Usuario(AbstractUser):
    filmes_vistos = models.ManyToManyField("Filme")

video/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms


class FormHomepage(forms.Form):
    email = forms.EmailField(label=False)

class CriarContaForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = Usuario
        fields = (
            'username',
            'email',
            'password1',
            'password2',
        )

    def clean_email(self):
        email = self.cleaned_data['email']
        if Usuario.objects.filter(email=email).exists():
            raise forms.ValidationError(
                "Este e-mail já está cadastrado em outra conta! Por favor, utilize outro endereço de e-mail.")
        return email

video/views.py
from django.shortcuts import redirect, reverse
from .models import Filme, Usuario
from .forms import CriarContaForm, FormHomepage
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .new_context import lista_todos


# Create your views here.
class HomePage(FormView):
    template_name = "homepage.html"
    form_class = FormHomepage

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('video:homevideos')
        else:
            return super().get(request, *args, **kwargs)

    def get_success_url(self):
        email = self.request.POST.get("email")
        usuarios = Usuario.objects.filter(email=email)
        if usuarios:
            return reverse("video:login")
        else:
            return reverse("video:criarconta")

# url - view - html
class HomeVideos(LoginRequiredMixin, ListView):
    template_name = "homevideos.html"
    model = Filme

    def get_context_data(self, **kwargs):
        context = super(HomeVideos, self).get_context_data(**kwargs)
        context.update(lista_todos(self.request))  # Add the 'lista_todos_filmes' to the context
        return context

class DetalhesVideos(LoginRequiredMixin, DetailView):
    template_name = "detalhesvideo.html"
    model = Filme

    def get(self, request, *args, **kwargs):
        filme = self.get_object()
        filme.visualizacoes += 1
        filme.save()
        usuario = request.user
        usuario.filmes_vistos.add(filme)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DetalhesVideos, self).get_context_data(**kwargs)
        videos_relacionados = Filme.objects.filter(categoria=self.get_object().categoria)[0:5]
        context["videos_relacionados"] = videos_relacionados
        return context

class PesquisaVideo(LoginRequiredMixin, ListView):
    template_name = "pesquisa.html"
    model = Filme

    def get_queryset(self):
        pesquisa = self.request.GET.get('query')
        if pesquisa:
            object_list = self.model.objects.filter(titulo__icontains=pesquisa, descricao__icontains=pesquisa)
            return object_list
        else:
            return None
class EditarPerfil(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = "editarperfil.html"
    model = Usuario
    fields = ["first_name", "last_name", "email"]

    def test_func(self):
        user = self.get_object()
        return self.request.user == user

    def get_success_url(self):
        return reverse("video:homevideos")

class CriarConta(FormView):
    template_name = "criarconta.html"
    form_class = CriarContaForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('video:login')

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>
        {% block titulo %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.tailwindcss.com"></script>

    {% block head %}
    {% endblock %}
</head>
<body class="bg-black text-gray-100 font-primary">
    {% include 'navbar.html' %}

    {% block content %}
    {% endblock %}

    <script>
        const nav = document.querySelector('nav')

        document.addEventListener("scroll",e=>{
            if(scrollY>100){
                if(scrollY>window.innerHeight){
                nav.classList.add('invisible')
            }else{
                nav.classList.add('bg-gray-900')
                nav.classList.remove('invisible')
            }
            }else{
                nav.classList.remove('bg-gray-900')
                nav.classList.remove('invisible')
            }
        })
    </script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</body>
</html>

templates/navbar.html
{% load static %}

<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <div class="w-6/12">
        <a href="/">
            <img class="w-2/12" src="{% static 'images/video_flix_logo.jpg' %}">
        </a>
    </div>
    <div class="w-6/12 flex flex-nowrap justify-end">
        {% if user.is_authenticated %}
        <div class="mr-2">
            <form method="get" action="{% url 'video:pesquisavideo' %}">
                <input type="text" class="py-1 px-2 rounded-md text-black" name="query" value="{{ request.GET.query }}" placeholder="Pesquisar...">
                <input type="submit" value="">
            </form>
        </div>
        {% endif %}
        {% if user.is_authenticated %}
        <div class="mr-2">
            <a href="{% url 'video:logout' %}">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                    Logout
                </button>
            </a>
        </div>
        {% else %}
        <div class="mr-2">
            <a href="{% url 'video:login' %}">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                    Login
                </button>
            </a>
        </div>
        {% endif %}
        {% if user.is_authenticated %}
        <div class="mr-2">
            <a href="{% url 'video:editarperfil' user.pk %}">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                    Editar Perfil
                </button>
            </a>
        </div>
        {% endif %}
    </div>

</nav>

video/templates/criarconta.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Criar Conta
{% endblock %}

{% block content %}
    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat bg-cover bg-center"  style="background-image: url('{% static 'images/background.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Crie uma conta para continuar</legend>
                    {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 px-3 text-white w-full md:text-lg rounded-md" type="submit">Criar Conta</button>
            </form>
        </div>
    </header>
    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">
            <li>&copy; 2024</li>
            <li>Feito com Python (Django)</li>
            <li>Pedro Arigoni</li>
        </ul>
    </footer>
{% endblock %}

video/templates/detalhesvideo.html
{% extends 'base.html' %}

{% block titulo %}
Detalhesvideos VideoFlix
{% endblock %}

{% block head %}
<style>
    .outlined-text {
            font-size: 6xl;
            font-weight: bold;
            color: white;
            margin: 4px 0;
            -webkit-text-stroke: 2px black; /* Adiciona uma borda preta ao texto */
            text-stroke: 2px black; /* Adiciona uma borda preta ao texto */
    }
    .custom-button {
        border: 2px solid black; /* Adiciona uma borda preta ao botão */
    }
 </style>
{% endblock %}

{% block content %}

<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{ object.thumb.url }}');">
        <div>
            <h2 class="text-6xl font-semibold text-white outlined-text my-4">
                {{ object.titulo }}
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                {{ object.descricao|slice:":100" }}...
            </p>
            <div class="flex my-4">
                <a href="{{ object.episodios.first.video }}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md custom-button" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section>
    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-3xl font-medium">
                Descrição
            </h2>
            <div class="flex justify-left  items-center min-w-full  movie_lis">
                <p class="text-gray-100 text-lg">
                    {{ object.descricao }}
                    <br>
                    Visualizações: {{ object.visualizacoes }}
                </p>
            </div>

            <div style='margin-top:2rem;margin-bottom:2rem;'>
                <h2 class="text-gray-200 text-3xl font-medium">
                    Episódios
                </h2>
                {% for episodio in object.episodios.all %}
                    <h3 class='text-lg'>
                        <a href="{{ episodio.video }}">
                            <p>{{ forloop.counter }}: {{ episodio.titulo }}</p>
                        </a>
                    </h3>
                {% endfor %}
            </div>

        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Relacionados
            </h2>
            <div class="flex flex-wrap items-center min-w-full movie_lis">
                {% for video in videos_relacionados %}
                <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{% url 'video:detalhesvideos' video.pk %}">
                            <img src="{{ video.thumb.url }}" class="object-cover w-full h-full " alt="">
                    </a>

                </div>
                {% endfor %}
            </div>
        </div>
    </section>

</main>




{% endblock %}>

video/templates/editarperfil.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Editar Perfil
{% endblock %}

{% block content %}
 <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat bg-cover bg-center"  style="background-image: url('{% static 'images/background.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h2 class="text-2xl">{{ user.email }}</h2>
            <form method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Edite os campos abaixo para editar seu perfil</legend>
                    {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md" type="submit">Editar Perfil</button>
            </form>
            <small><a href="{% url 'video:mudarsenha' %}">Quer mudar sua senha?</a></small>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2024</li>
            <li>Feito com Python (Django)</li>
            <li>Pedro Arigoni</li>
        </ul>
    </footer>
{% endblock %}

video/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Home Page
{% endblock %}

{% block head %}
<style>
    #id_email{
        width: 100%;
        color: #000000;
        padding: 5px 5px;
    }
</style>
{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat bg-cover bg-center"  style="background-image: url('{% static 'images/background.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">

            <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
                Filmes e séries, tudo em um só lugar.
            </h1>
            <h3 class="text-xl md:text-xl py-5">
                Assista onde quiser. Cancele quando quiser.
            </h3>
            <h4 class="text-sm md:text-lg pb-3">
                Quer começar? Coloque seu e-mail abaixo para acessar.
            </h4>

            <div class="w-full flex justify-center">
                <div class="flex justify-center items-center w-11/12 md:w-10/12">
                    <form method="post" class="w-6/12 justify-center">
                        {% csrf_token %}
                        <div class="flex flex-grow items-stretch">
                            {{ form }}
                        <button class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                            <span>
                                Acessar
                            </span>
                            <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                        </button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
</header>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Enjoy on your TV.
            </h2>
            <h5 class="md:text-xl text-lg">
                Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/tv.png' %}" class="w-8/12" alt="">
        </div>
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class='md:w-1/2 flex justify-center items-center '>
            <img src="{% static 'images/mobile-0819.jpg' %}" class="w-8/12" alt="">
        </div>

        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Download your shows to watch offline.
            </h2>
            <h5 class="md:text-xl text-lg">
                Save your favorites easily and always have something to watch.
            </h5>
        </div>

    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Create profiles for kids.
            </h2>
            <h5 class="md:text-xl text-lg">
                Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/netflix_kid.png' %}" class="w-8/12" alt="">
        </div>
    </section>
    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2024</li>
            <li>Feito com Python (Django)</li>
            <li>Pedro Arigoni</li>
        </ul>
    </footer>

{% endblock %}

video/templates/homevideos.html
{% extends 'base.html' %}

{% block titulo %}
Home Videos
{% endblock %}

{% block head %}
<style>
    $itemGrow: 1.2;
    $duration: 250ms;

    html {
      scroll-behavior: smooth;
    }

    body {
      margin: 0;
      background-color: #000;
    }

    h1 {
      font-family: Arial;
      color: red;
      text-align: center;
    }

    .wrapper {
      display: grid;
      grid-template-columns: repeat(3, 100%);
      overflow: hidden;
      scroll-behavior: smooth;
    }

    // Remove the arrow for Mobile
    @media only screen and (max-width: 600px) {
      a.arrow__btn {
        display: none;
      }
    }

    .outlined-text {
        font-size: 6xl;
        font-weight: bold;
        color: white;
        margin: 4px 0;
        -webkit-text-stroke: 2px black; /* Adiciona uma borda preta ao texto */
        text-stroke: 2px black; /* Adiciona uma borda preta ao texto */
    }
    .custom-button {
        border: 2px solid black; /* Adiciona uma borda preta ao botão */
    }
</style>
{% endblock %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{{ video_destaque.thumb.url }}');">
        <div>
            <h2 class="text-6xl font-semibold text-white outlined-text my-4">
                {{ video_destaque.titulo }}
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                {{ video_destaque.descricao }}
            </p>
            <div class="flex my-4">
                <a href="{% url 'video:detalhesvideos' video_destaque.pk %}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md custom-button" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium " >
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section>


    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Novo
            </h2>
            <div class="wrapper">
              <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section2" class="arrow__btn text-6xl page">‹</a>
                  {% for  filme in lista_videos_recentes %}
                      {% if forloop.counter < 5 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'video:detalhesvideos' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                <p>{{ filme.titulo }}</p>
                              </a>
                          </div>
                      {% endif %}
                  {% endfor %}
                    <a href="#section2" class="arrow__btn text-6xl">›</a>
              </section>
                {% if lista_videos_recentes|length > 4 %}
                  <section id="section2" class="flex flex-nowrap items-center justify-center">
                    <a href="#section1" class="arrow__btn text-6xl">‹</a>
                      {% for  filme in lista_videos_recentes %}
                        {% if forloop.counter > 4 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'video:detalhesvideos' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                <p>{{ filme.titulo }}</p>
                              </a>
                          </div>
                        {% endif %}
                      {% endfor %}
                    <a href="#section1" class="arrow__btn text-6xl">›</a>
                  </section>
                {% endif %}
            </div>


        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Em Alta
            </h2>
            <div class="wrapper">
              <section id="section1emalta" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section2emalta" class="arrow__btn text-6xl page">‹</a>
                  {% for  filme in lista_mais_assistidos %}
                      {% if forloop.counter < 5 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'video:detalhesvideos' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                <p>{{ filme.titulo }}</p>
                              </a>
                          </div>
                      {% endif %}
                  {% endfor %}
                    <a href="#section2emalta" class="arrow__btn text-6xl">›</a>
              </section>
                {% if lista_mais_assistidos|length > 4 %}
                  <section id="section2emalta" class="flex flex-nowrap items-center justify-center">
                    <a href="#section1emalta" class="arrow__btn text-6xl">‹</a>
                      {% for  filme in lista_mais_assistidos %}
                        {% if forloop.counter > 4 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'video:detalhesvideos' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                <p>{{ filme.titulo }}</p>
                              </a>
                          </div>
                        {% endif %}
                      {% endfor %}
                    <a href="#section1emalta" class="arrow__btn text-6xl">›</a>
                  </section>
                {% endif %}
            </div>


        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Continuar Assistindo
            </h2>
            <div class="wrapper">
              <section id="section1vistos" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section2vistos" class="arrow__btn text-6xl page">‹</a>
                  {% for  filme in request.user.filmes_vistos.all %}
                      {% if forloop.counter < 5 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'video:detalhesvideos' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                <p>{{ filme.titulo }}</p>
                              </a>
                          </div>
                      {% endif %}
                  {% endfor %}
                    <a href="#section2vistos" class="arrow__btn text-6xl">›</a>
              </section>
                {% if request.user.filmes_vistos.all|length > 4 %}
                  <section id="section2vistos" class="flex flex-nowrap items-center justify-center">
                    <a href="#section1vistos" class="arrow__btn text-6xl">‹</a>
                      {% for  filme in request.user.filmes_vistos.all %}
                        {% if forloop.counter > 4 %}
                          <div class="item h-64 w-1/4 m-4">
                              <a href="{% url 'video:detalhesvideos' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                <p>{{ filme.titulo }}</p>
                              </a>
                          </div>
                        {% endif %}
                      {% endfor %}
                    <a href="#section1vistos" class="arrow__btn text-6xl">›</a>
                  </section>
                {% endif %}
            </div>


        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Todos os Vídeos
            </h2>
            <div class="wrapper">
                  <section id="todosvideos" class="flex flex-wrap items-center justify-center space-x-8">
                       {% for filme in lista_todos_filmes %}
                            <div class="item h-64 w-1/5 m-4">
                                <a href="{% url 'video:detalhesvideos' filme.pk %}">
                                    <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                    <p>{{ filme.titulo }}</p>
                                </a>
                            </div>
                       {% endfor %}
                  </section>

            </div>
        </div>
    </section>
</main>

{% endblock %}

video/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Fazer Login
{% endblock %}

{% block content %}
    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat bg-cover bg-center"  style="background-image: url('{% static 'images/background.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Faça Login para continuar</legend>
                    {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 my-2 px-3 w-full text-white md:text-lg rounded-md" type="submit">Fazer Login</button>
            </form>
            <small>
                Não tem uma conta ainda? <p><a href="{% url 'video:criarconta' %}">Clique aqui para criar uma conta</a></p>
            </small>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2024</li>
            <li>Feito com Python (Django)</li>
            <li>Pedro Arigoni</li>
        </ul>
    </footer>
{% endblock %}

video/templates/pesquisa.html
{% extends 'base.html' %}

{% block titulo %}
Pesquisa de Vídeos
{% endblock %}

{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Resultados da Busca
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                  {% for filme in object_list %}
                    <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                        <a href="{% url 'video:detalhesvideos' filme.pk %}">
                          <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt="">
                        </a>
                    </div>
                  {% endfor %}
                </div>
            </div>
        </section>
    </main>
{% endblock %}